---
app_name: taskflow
app_user: ubuntu
app_dir: /opt/taskflow
github_repo: https://github.com/ashyT-Cloud/production-server-automation.git

ansible_user: ubuntu
ansible_ssh_private_key_file: /home/ubuntu/microservice-key.pem
