---
plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  tag:Project: production-server-automation
  tag:Role: application-server
  instance-state-name: running

hostnames:
  - tag:Name

compose:
  ansible_host: public_ip_address

keyed_groups:
  - key: tags.Role
    prefix: role
